#
# BisqueCore - TurboGears 2 testing environment configuration
#
[DEFAULT]
debug = true

[server:main]
use = egg:Paste#http
host = 0.0.0.0
port = 5000

[app:main]
use = egg:bqfeature
sqlalchemy.url = postgresql://bisque:bisque2022@postgres:5432/bisque
skip_authentication = true

[test]
host.root= http://localhost:8080
host.user= admin
host.password= admin

[store]
samples_url= http://localhost:8080/samples/
input_dir= /tmp/test_inputs
results_dir= /tmp/test_results
files= test1.jpg test2.png
